name: Package

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"
          include-prerelease: true

      - name: Build
        run: dotnet publish --configuration Release --output out

      - name: Archive
        run: |
          Compress-Archive "out/*" LockMicrosoftPinyin.zip

      - name: Tag
        run: |
          echo "release_tag=$(date '+%Y-%m-%d')" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.release_tag }}
          files: LockMicrosoftPinyin.zip
